### ISSUE TITLE
Update version 

### ISSUE THREAD

**Issue by vwmaus** [fineprint-global/io-visualization#2]
@Gutschlhofer, maybe you can use the latest release version `3.6.0` if available for shiny-verse
https://github.com/fineprint-global/io-visualization/blob/d430032e1ab241c810fddf15f141cec8b4a4a1f1/docker-rshiny/Dockerfile#L2

**Comment by vwmaus** [comment]
docker-compose also has the latest release version `3.7`
https://github.com/fineprint-global/io-visualization/blob/d430032e1ab241c810fddf15f141cec8b4a4a1f1/docker-compose.yml#L1

**Comment by Gutschlhofer** [comment]
I will keep the shiny-verse update in mind - as of right now I develop using R `3.5.2` on our server so there might be unexpected problems when using R `3.6`, so I'll stay on the safe side for now but consider updating in the future.
