### ISSUE TITLE
Add more details to the repo

### ISSUE THREAD

**Issue by vwmaus** [fineprint-global/io-visualization#3]
@Gutschlhofer, you could add more details about the app to [README.md](https://github.com/fineprint-global/io-visualization/blob/master/README.md). 

Dependencies:
- [x] What are the software dependencies to run the app? What should I install before I can run the app? Only docker-compose? 

Usage: 
- [x] How to run the app? 
- [x] Add instructions to create `.env` and `.Renviron`.
- [x] What is the sequence of commands? 
- [x] Do I have to open the browser? Which port? e.g., [http://localhost:80](http://localhost:80)
- [x] How can I stop or restart the app? 

Development:
- [x] How to further develop using this repo? Which files to edit? 
- [x] Where to add further R package dependencies (Dockerfile)? 

Acknowledgement:
- [x] This project gratefully acknowledges financial support from the ERC/FINEPRINT/XXXXX!

**Comment by Gutschlhofer** [comment]
The things mentioned should all be done for a while now, so I am closing this issue.
